import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import {getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import {getFirestore,collection,getDocs,doc,getDoc,setDoc,updateDoc,writeBatch} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js'; import {presenters as defaults, criteria} from './presenters.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let role=null,lastVotes=[],presenters=[],votingOpen=false;
function ownerUI(){document.querySelectorAll('.ownerOnly').forEach(x=>x.classList.toggle('hidden',role!=='owner'));$('roleText').textContent=`Signed in as ${auth.currentUser?.email||''} — ${role||'unauthorized'}`}
onAuthStateChanged(auth,async u=>{if(!u){role=null;$('login').classList.remove('hidden');$('dash').classList.add('hidden');return}try{const r=await getDoc(doc(db,'moderators',u.uid));role=r.exists()?r.data().role:null;if(!['owner','moderator'].includes(role))throw Error('This account is not an approved moderator.');$('login').classList.add('hidden');$('dash').classList.remove('hidden');ownerUI();await refresh()}catch(e){$('loginMsg').textContent=e.message;await signOut(auth)}});
$('loginBtn').onclick=async()=>{try{$('loginMsg').textContent='';await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value)}catch(e){$('loginMsg').textContent=e.message}};$('logout').onclick=()=>signOut(auth);
function calcRows(){return presenters.map(p=>{const v=lastVotes.filter(x=>x.presenterId===p.id),avg=k=>v.length?v.reduce((a,x)=>a+(+x[k]||0),0)/v.length:0;const vals=Object.fromEntries(criteria.map(([k])=>[k,avg(k)]));return {...p,...vals,final:criteria.reduce((a,[k])=>a+vals[k],0)/criteria.length,votes:v.length}}).sort((a,b)=>b.final-a.final||b.votes-a.votes||a.id.localeCompare(b.id))}
async function refresh(){const [vs,ps,es]=await Promise.all([getDocs(collection(db,'votes')),getDocs(collection(db,'presenters')),getDoc(doc(db,'event','settings'))]);lastVotes=vs.docs.map(d=>d.data());presenters=ps.docs.map(d=>({id:d.id,...d.data()}));votingOpen=es.exists()&&es.data().votingOpen===true;$('toggleVoting').textContent=votingOpen?'Close voting':'Open voting';$('toggleVoting').className=votingOpen?'danger':'';const rows=calcRows();$('ranking').innerHTML=rows.map((r,i)=>`<tr><td>${i+1}</td><td>${r.id} — ${esc(r.name)}</td><td>${r.room}</td>${criteria.map(([k])=>`<td>${r[k].toFixed(2)}</td>`).join('')}<td><b>${r.final.toFixed(2)}</b></td><td>${r.votes}</td>${role==='owner'?`<td><button class="small edit" data-id="${r.id}">Edit</button></td>`:''}</tr>`).join('');document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>editPresenter(b.dataset.id));$('winners').innerHTML=[1,2,3].map(room=>{const top=rows.filter(r=>+r.room===room).slice(0,3);return `<div class="winnerbox"><h3>Room ${room}</h3>${top.map((r,i)=>`<p><b>${['🥇','🥈','🥉'][i]} ${r.id} — ${esc(r.name)}</b><br>${r.final.toFixed(2)} · ${r.votes} votes</p>`).join('')||'<p>No presenters yet.</p>'}</div>`}).join('');$('status').textContent=`${lastVotes.length} submitted scores · Voting ${votingOpen?'OPEN':'CLOSED'}.`;return rows}
$('refresh').onclick=refresh;
$('toggleVoting').onclick=async()=>{if(!['owner','moderator'].includes(role))return;await updateDoc(doc(db,'event','settings'),{votingOpen:!votingOpen});await refresh()};
$('seed').onclick=async()=>{if(role!=='owner')return;if(!confirm('Create/update the 30 presenter records from presenters.js?'))return;for(let i=0;i<defaults.length;i+=400){const b=writeBatch(db);defaults.slice(i,i+400).forEach(p=>b.set(doc(db,'presenters',p.id),{name:p.name,room:p.room,title:p.title},{merge:true}));await b.commit()}await refresh();alert('Presenter records synchronized.')};
async function editPresenter(id){if(role!=='owner')return;const p=presenters.find(x=>x.id===id);const name=prompt(`Name for ${id}:`,p.name);if(name===null)return;const title=prompt(`Research title for ${id}:`,p.title||'');if(title===null)return;await setDoc(doc(db,'presenters',id),{name:name.trim()||p.name,title:title.trim(),room:p.room},{merge:true});await refresh()}
$('reset').onclick=async()=>{if(role!=='owner')return;const typed=prompt('This permanently deletes ALL submitted votes. Type RESET ALL VOTES to continue.');if(typed!=='RESET ALL VOTES')return;const snap=await getDocs(collection(db,'votes'));for(let i=0;i<snap.docs.length;i+=400){const b=writeBatch(db);snap.docs.slice(i,i+400).forEach(d=>b.delete(d.ref));await b.commit()}await refresh();alert('All votes deleted. Presenter and moderator records were kept.')};
$('export').onclick=async()=>{const rows=await refresh(),wb=XLSX.utils.book_new();const rank=rows.map((r,i)=>({Rank:i+1,ID:r.id,Presenter:r.name,Room:r.room,Title:r.title,Clarity:r.clarity,Engagement:r.engagement,Significance:r.significance,Delivery:r.delivery,'Final Score':r.final,Votes:r.votes}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rank),'Ranking');[1,2,3].forEach(room=>{const rr=rows.filter(r=>+r.room===room).map((r,i)=>({Rank:i+1,ID:r.id,Presenter:r.name,Title:r.title,'Final Score':r.final,Votes:r.votes}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rr),`Room ${room}`)});presenters.sort((a,b)=>a.id.localeCompare(b.id)).forEach(p=>{const data=lastVotes.filter(v=>v.presenterId===p.id).map((v,i)=>({Vote:i+1,Clarity:v.clarity,Engagement:v.engagement,Significance:v.significance,Delivery:v.delivery,Average:(v.clarity+v.engagement+v.significance+v.delivery)/4}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data.length?data:[{Vote:'No votes'}]),p.id)});XLSX.writeFile(wb,'NUSGSS_3MT_Results.xlsx')};
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
