import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {getFirestore,collection,getDocs,doc,setDoc,writeBatch} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import {firebaseConfig,MODERATOR_EMAIL} from './firebase-config.js'; import {presenters,criteria} from './presenters.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let lastVotes=[];
onAuthStateChanged(auth,u=>{const ok=u&&u.email===MODERATOR_EMAIL;$('login').classList.toggle('hidden',ok);$('dash').classList.toggle('hidden',!ok);if(ok)refresh()});
$('loginBtn').onclick=async()=>{try{await signInWithEmailAndPassword(auth,$('email').value,$('password').value)}catch(e){$('loginMsg').textContent=e.message}};$('logout').onclick=()=>signOut(auth);
async function refresh(){const snap=await getDocs(collection(db,'votes'));lastVotes=snap.docs.map(d=>d.data());const rows=presenters.map(p=>{const v=lastVotes.filter(x=>x.presenterId===p.id), avg=k=>v.length?v.reduce((a,x)=>a+(+x[k]||0),0)/v.length:0;const vals=Object.fromEntries(criteria.map(([k])=>[k,avg(k)]));return {...p,...vals,final:criteria.reduce((a,[k])=>a+vals[k],0)/criteria.length,votes:v.length}}).sort((a,b)=>b.final-a.final||b.votes-a.votes);$('ranking').innerHTML=rows.map((r,i)=>`<tr><td>${i+1}</td><td>${r.id} — ${r.name}</td><td>${r.room}</td>${criteria.map(([k])=>`<td>${r[k].toFixed(2)}</td>`).join('')}<td><b>${r.final.toFixed(2)}</b></td><td>${r.votes}</td></tr>`).join('');$('status').textContent=`${lastVotes.length} votes recorded.`;return rows}$('refresh').onclick=refresh;
function randomCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='GSS-';for(let i=0;i<6;i++)s+=chars[Math.floor(Math.random()*chars.length)];return s}
$('seed').onclick=async()=>{if(!confirm('Create 150 new anonymous voting codes?'))return;const batch=writeBatch(db),codes=[];for(let i=0;i<150;i++){const c=randomCode();codes.push(c);batch.set(doc(db,'tokens',c),{active:true})}await batch.commit();$('codes').value=codes.join('\n');$('status').textContent='150 voting codes created. Save/print them now.'};
$('reset').onclick=async()=>{const typed=prompt('Type RESET ALL VOTES to permanently delete all votes.');if(typed!=='RESET ALL VOTES')return;const snap=await getDocs(collection(db,'votes'));for(let i=0;i<snap.docs.length;i+=400){const b=writeBatch(db);snap.docs.slice(i,i+400).forEach(d=>b.delete(d.ref));await b.commit()}await refresh();alert('All votes deleted. Voting codes were kept.')};
$('export').onclick=async()=>{const rows=await refresh(),wb=XLSX.utils.book_new();const rank=rows.map((r,i)=>({Rank:i+1,ID:r.id,Presenter:r.name,Room:r.room,Title:r.title,Clarity:r.clarity,Engagement:r.engagement,Significance:r.significance,Delivery:r.delivery,'Final Score':r.final,Votes:r.votes}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rank),'Ranking');presenters.forEach(p=>{const data=lastVotes.filter(v=>v.presenterId===p.id).map((v,i)=>({Vote:i+1,Clarity:v.clarity,Engagement:v.engagement,Significance:v.significance,Delivery:v.delivery,Average:(v.clarity+v.engagement+v.significance+v.delivery)/4}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data.length?data:[{Vote:'No votes'}]),p.id)});XLSX.writeFile(wb,'NUSGSS_3MT_Results.xlsx')};
