import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import {getAuth,signInAnonymously,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import {getFirestore,collection,getDocs,doc,getDoc,setDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';
import {criteria} from './presenters.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let user=null,presenters=[],open=false;const scores={};
criteria.forEach(([k,label])=>{scores[k]=0;const d=document.createElement('div');d.className='criterion';d.innerHTML=`<label>${label}</label><div class="stars" data-k="${k}">${[1,2,3,4,5].map(n=>`<button type="button" data-n="${n}">${n}</button>`).join('')}</div>`;$('criteria').appendChild(d)});
document.querySelectorAll('.stars button').forEach(b=>b.onclick=()=>{const p=b.parentElement,k=p.dataset.k,n=+b.dataset.n;scores[k]=n;[...p.children].forEach(x=>x.classList.toggle('on',+x.dataset.n<=n))});
function loadRoom(){const room=+$('room').value,arr=presenters.filter(p=>+p.room===room).sort((a,b)=>a.id.localeCompare(b.id));$('presenter').innerHTML=arr.length?arr.map(p=>`<option value="${p.id}">${p.id} — ${p.name}</option>`).join(''):'<option>No presenters loaded</option>';showTitle()}
function showTitle(){const p=presenters.find(x=>x.id===$('presenter').value);$('title').textContent=p?.title||''}
$('room').onchange=loadRoom;$('presenter').onchange=showTitle;
async function init(){try{if(!auth.currentUser)await signInAnonymously(auth);user=auth.currentUser;const [ps,es]=await Promise.all([getDocs(collection(db,'presenters')),getDoc(doc(db,'event','settings'))]);presenters=ps.docs.map(d=>({id:d.id,...d.data()}));open=es.exists()&&es.data().votingOpen===true;$('eventState').textContent=open?'Voting is OPEN':'Voting is CLOSED';$('eventState').className='statuspill '+(open?'open':'closed');$('submit').disabled=!open||!presenters.length;const q=new URLSearchParams(location.search).get('room');if(['1','2','3'].includes(q)){$('room').value=q;$('room').disabled=true}loadRoom()}catch(e){$('msg').textContent='Could not connect: '+e.message}}
onAuthStateChanged(auth,u=>{if(u&&!user)init()});if(!auth.currentUser)signInAnonymously(auth).catch(e=>$('msg').textContent=e.message);else init();
$('submit').onclick=async()=>{const pid=$('presenter').value;$('msg').textContent='';if(!open)return $('msg').textContent='Voting is currently closed.';if(!pid||criteria.some(([k])=>!scores[k]))return $('msg').textContent='Please score every criterion.';try{const ref=doc(db,'votes',`${user.uid}_${pid}`);if((await getDoc(ref)).exists())throw Error('You have already scored this presenter on this browser.');await setDoc(ref,{voterUid:user.uid,presenterId:pid,...scores,createdAt:serverTimestamp()});$('msg').textContent='✓ Vote recorded. Thank you!';criteria.forEach(([k])=>scores[k]=0);document.querySelectorAll('.stars button').forEach(x=>x.classList.remove('on'))}catch(e){$('msg').textContent=e.message}}
